### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by elsehow** [elsehow/moneybot#14]
We have a test.py, why not add some CI? Will help us when we have more contributors.

**Comment by adamrothman** [comment]
@elsehow Apparently only a repo administrator can do the initial setup for Travis. How do you want to proceed?

**Comment by elsehow** [comment]
I added enabled the repo in Travis's UI. It looks like `.travis.yml` *should* handle everything else

**Comment by adamrothman** [comment]
Closed by a314082ece3b00618e5022806df19b8476591db1
