### ISSUE TITLE
Reduce/remove testing dependency on historical data

### ISSUE THREAD

**Issue by adamrothman** [elsehow/moneybot#18]
Right now the main functionality test for moneybot relies on a fully-populated historical dataset. At 163 MB this is not a trivial thing to throw around and having to load it before test runs is going to make #14 very difficult. So, here are two proposals for how to solve this, in order of awesomeness:

1. Completely mock out calls to InfluxDB during testing. This would be my preference as it completely frees the testing setup of external dependencies and will make CI much, much simpler. We would manually craft the responses we expect to get for a given set of queries and mock out the appropriate calls to return these responses. This lets us test what we actually care about: whether `moneybot` does the right thing with the data it gets from InfluxDB (as opposed to whether we can set up InfluxDB the right way).

2. Create a much smaller dataset that can be used for testing. This is less ideal, as it still requires us to make an instance of InfluxDB available to the tests.

Let me know what you guys think. I'm happy to handle this one, I just don't know what kind of data we should be expecting to get from InfluxDB.

**Comment by elsehow** [comment]
Agreed, we need a mini-dataset for testing purposes.

I also prefer the mock strategy. 

The easiest way to get some mock data is simply to log the Influx queries we're making when the tests run, then fetch those data offline and save 'em as JSON somewhere.

Does this seem reasonable?

**Comment by adamrothman** [comment]
That seems reasonable. Do the calls to InfluxDB return JSON dicts directly? Or would you need to massage it into rows/whatever?

**Comment by elsehow** [comment]
You need to do a little bit of marshaling, but nothing too atrocious. The extent of what we do to return the current chart data, for example, is [just a list comprehension](https://github.com/elsehow/moneybot/blob/master/moneybot/markets/history.py#L168).

**Comment by elsehow** [comment]
I will wait on #21 before making a mock.
