### ISSUE TITLE
Use shared singleton instances for InfluxDBClient and Poloniex

### ISSUE THREAD

**Issue by adamrothman** [elsehow/moneybot#21]
As far as I can tell there isn't a need for each object that wants to talk to these services to instantiate its own instance of `influxdb.InfluxDBClient` or `poloniex.Poloniex`. A common pattern is to use a shared singleton.

**Comment by elsehow** [comment]
Agreed. 

For context: right now we have 2 Poloniex clients, one for the `LiveMarketAdapter`, and one for the scraping routine that `MarketHistory` does.

We only have one InfluxDB client right now (in `MarketHistory`), but that'll change soon, as we'll have `LiveMarketAdapter` recording its attempted (and successful) trades (see #8).
