### ISSUE TITLE
Use YAML for config files

### ISSUE THREAD

**Issue by adamrothman** [elsehow/moneybot#23]
The syntax is much easier to read and write without fucking it up.

**Comment by elsehow** [comment]
While you're at it, the default db port should be the same as the default Docker Influx port (rather than localhost), if that's our recommendation.

**Comment by adamrothman** [comment]
The port is actually the same if you run it with the recommended settings. What I have done in the past is to add a Makefile that creates/starts the container so we don't have to remember which flags are necessary.
