### ISSUE TITLE
Restore script uses weird template strings

### ISSUE THREAD

**Issue by elsehow** [elsehow/moneybot#30]
In the `restore.sh` script, env vars are referenced like

`${VARNAME}`

In my environments (bash, zsh), vars are referenced like

`$VARNAME`

and the current script doesn't work. Am I missing something? Or was that script created in some other environment?

**Comment by adamrothman** [comment]
Just for reference, or the curious:

`${VARNAME}` is (should be?) safe in any shell language. It's used when you want to avoid ambiguity about what is part of the variable name and what isn't. Suppose you have an env var `SOME` that you want to substitute into an expression – this is confusing (for humans and computers):

`cat ~/$SOMEFILE.txt`

Whereas this is not:

`cat ~/${SOME}FILE.txt`
