### ISSUE TITLE
make: docker: No such file or directory

### ISSUE THREAD

**Issue by JakeHartnell** [elsehow/moneybot#37]
When I try `make image` I get the following (I have Docker for mac installed...): 

```
make: docker: No such file or directory
make: *** [image] Error 1
```

I actually solved this myself, but I'm posting in case someone comes across the same problem... you need be running the docker daemon.

**Comment by JakeHartnell** [comment]
For mac: https://docs.docker.com/docker-for-mac/

**Comment by adamrothman** [comment]
I would actually recommend installing `docker-machine` with Homebrew. Docker for Mac abstracts away too much of what's going on (IMO) behind its UI.

**Comment by elsehow** [comment]
I also had some terrible `PATH` experiences with Docker for Mac. `docker-machine` works the same as on all other POSIX systems (as far as I can tell).

**Comment by JakeHartnell** [comment]
`docker-machine` is much better.
