### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by JakeHartnell** [elsehow/moneybot#38]
Will make a PR with some readme revisions, but got stuck during the `./restore.sh` step:

```
(venv) Jakes-MacBook-Pro-4:postgres JakeHartnell$ ./restore.sh
Downloading latest release
./restore.sh: line 8: wget: command not found
Restoring database to dockerized
psql: could not connect to server: Operation timed out
	Is the server running on host "192.168.99.100" and accepting
	TCP/IP connections on port 5432?
Cleaning up artifacts
rm: ./2017-07-14.sql: No such file or directory
```

**Comment by JakeHartnell** [comment]
I made the server...
```
make server
docker run -d \
	-e "POSTGRES_PASSWORD=secretpass" \
	-p 5432:5432 \
	--name postgres \
	postgres:9.6
docker: Error response from daemon: Conflict. The container name "/postgres" is already in use by container 2de7cba9366ff73497f2ad8a3d11230ee6766e7564a0c41b73e28c4bb3a30e3d. You have to remove (or rename) that container to be able to reuse that name..
```

**Comment by elsehow** [comment]
You may need to start your docker machine, and/set your docker environment variables.

For example, I start my docker machine with

```
docker-machine start dev
```

and set relevant environment variables with

```
eval $(docker-machine env dev)
```

One possibility is that your docker machine is running on some different IP. You can run `docker-machine env [my-machine-name]` to see what host it's running on.

**Comment by adamrothman** [comment]
Are you using Docker for Mac or `docker-machine`? `restore.sh` assumes your docker host is at 192.168.99.100, but Docker for Mac may assign a different address.

**Comment by adamrothman** [comment]
Sorry I didn't actually read the error – @JakeHartnell it looks like you already have a container with the name postgres, and you can't have more than one container with the same name. You can run `docker ps -a` to see all the containers on your host (`-a` includes the stopped ones as well). Use `docker rm <container name>` to clean up old ones.

**Comment by JakeHartnell** [comment]
> Are you using Docker for Mac or docker-machine? restore.sh assumes your docker host is at 192.168.99.100, but Docker for Mac may assign a different address.

That's the issue. : ) Thanks.

**Comment by JakeHartnell** [comment]
One last note in case anyone else on OSX has this problem, and stumbles across this thread.

After running `docker-machine env [my-machine-name]` I noticed the port was different from what was listed in `config.yml`. Updating `config.yml` to match the correct port and IP made it work like a charm.
