### ISSUE TITLE
Support non-BTC starting balances

### ISSUE THREAD

**Issue by adamrothman** [elsehow/moneybot#45]
Running a backtest with starting balances `{'ETH': 1.0}` doesn't simulate any trades. It's easy enough to convert everything into BTC before running moneybot, but we should let people start with whatever they have.

To reproduce this, set your starting balances as above in `examples/backtest.py` and run a backtest with the log level set to DEBUG:
```
python3 examples/backtest.py -c config.yml -s buffed-coin -l DEBUG
```

You won't see any log lines starting with "Simulating trade:" – compare this to what you get starting with BTC, which has many trades.

**Comment by adamrothman** [comment]
[`Strategy::initial_proposed_trades`](https://github.com/elsehow/moneybot/blob/e095fbf4095aefea6c8a4c8d08b0e2810175d7f3/moneybot/strategy.py#L161) assumes starting balance is entirely in "fiat" which seems like the thing we need to change.

**Comment by elsehow** [comment]
One solution might be to think less about trades to execute, and more about what distribution of assets we want. In the domain logic of the index fund, that's really what we care about. Of course, that would be a fairly significant refactor....

So, an intermediate hack would just be to check that we have a sufficiently diversified portfolio (in the context of our example strategies, that we have at least *some* balance of all the coins on Polo).
