### ISSUE TITLE
Deprecate `ProposedTrade`

### ISSUE THREAD

**Issue by elsehow** [elsehow/moneybot#47]
Right now, we use the `ProposedTrade` type to discuss trades that have not yet been executed.

However, this type rolls together a few concerns that we would do well to separate out.

Also, there is a big mess [in state.py](https://github.com/elsehow/moneybot/blob/fcd3a98b8140edecc07ce9585237a1e9f8fd3aea/moneybot/market/state.py#L94-L110), where we try to look up values by market name, trying one order of currencies first, and trying the other if it fails. This is some problem with the way `balances` interacts with `MarketState`. Even worse,  if a currency disappears during that trading step, [we mutate `balances` out of scope](https://www.youtube.com/watch?v=rpj39Znv0oA) by removing it.

We cannot solve all of these issues at once, but we can take some intermediate step 
So here's the proposal:

- a type `AbstractTrade(from coin, to coin, reference coin, reference value)`
- a type `Order(market, amount, price, direction` (where `direction` is `'buy'` or `'sell'`)

Orders would be produced from `AbstractTrade`s using a method

    f(AbstractTrade, MarketState) -> Order

`AbstractTrade` allows us to describe trades in terms of some reference currency, so that we can talk about the /value/ of the currency we wish to trade (e.g. in USD(T)).

`Order`s are consumable by market APIs.

We can also use this as an opportunity to introduce some testing deeper into moneybot internals (see #48).

This strategy could help us address #33.

**Comment by adamrothman** [comment]
I think `f` is probably an instance method on `MarketAdapter` (since each exchange will have its own idea of what constitutes an `Order`), e.g. `MarketAdapter::create_orders(self, trades: List[AbstractTrade], market_state: MarketState) -> List[Order]`.

**Comment by elsehow** [comment]
Right, we want that to be a `List[Order]`, because we may (someday) have to execute multiple `Order`s in order to trade some currency X for some currency Y.

**Comment by adamrothman** [comment]
Right, so it's probably actually more like

```python
def _orders_for_trade(self, trade: AbstractTrade, market_state: MarketState) -> List[Order]:
    ...

def orders_for_trades(self, trades: List[AbstractTrade], market_state: MarketState) -> List[Order]:
    return list(itertools.chain(self._orders_for_trade(t) for t in trades))
```

**Comment by elsehow** [comment]
I would probably have `orders_for_trades` close over the method `_orders_for_trade`, but I agree.

**Comment by elsehow** [comment]
`Strategy::propose_trades_for_total_rebalancing` and `Strategy::propose_trades_for_partial_rebalancing` are substantially identical, and what they have in common is logic around "fanning in" and "fanning out."

I actually propose we describe the general method for diffing `observed` and `desired` `market_state.balance`s, and coming up with the list of orders


if `AbstractTrade` and `Order` fall out of this process, we will implement them, but I think this diffing should take priority. Otherwise, we'll spend more time fixing weird bugs that shouldn't be there at all.

**Comment by elsehow** [comment]
There are no guarantees the market will execute the order we expect, so there is definitely some room for error there. That's a general statement about planning trades ahead.

Some trades have no dependencies:

```
X -> Y
Z -> A
```

However, some trades do:

```
X -> Y -> Z
```

or:

```
(X, Y) -> Z -> (A, B)
```


That last example is kind of like our current fan-in, fan-out scenario.

What we're interested in is the case where the order we propose does *NOT* get filled exactly the way we propose it. The way to deal with this case  would be to come up with a new proposal, *and* go back to the drawing board with regard to our planned future trades.

What we're describing here is an algorithm that can actually hit a target asset allocation, even when market conditions change. Such a routine would also solve #33.
