### ISSUE TITLE
Include times in logging

### ISSUE THREAD

**Issue by elsehow** [elsehow/moneybot#49]
It would be nice if the logger included a timestamp. It makes it easier to see when the last run step occurred, how long the trades took to execute, etc.

**Comment by adamrothman** [comment]
@elsehow my changes in #46 incorporate this, at least for live trading.

**Comment by elsehow** [comment]
Perfect, let's make note that #46 closes this issue

**Comment by elsehow** [comment]
Re-opening - we want to know when the steps occurred
